#!/usr/bin/env python3
"""compare_k2_k3.py -- quantify the K2 (per-sentence) -> K3/K5 (batched) win.

Joins the two benchmark CSVs on K and reports the improvement in a single
markdown file + overlay plots, WITHOUT touching either benchmark's own outputs.

Inputs (same columns; make_benchmark_md.py-compatible):
  kbest_bench.csv         Week-7 per-sentence K2 driver  (cushr_kbest)
  batched_bench.csv       Week-8 batched K3/K5 driver    (cushr_batched, --batch -1)
  batched_bench_b<N>.csv  optional: batched runs at batch size N (memory sweep)

Outputs (next to this script, distinct filenames):
  COMPARISON.md
  comparison_throughput.png     wall + kernel sent/sec, K2 vs K3, vs K
  comparison_memory.png         used MB vs batch size (K3) with K2 fixed baseline

IMPORTANT (methodology): the batched win has TWO components.
  1. WALL timing (us_per_sent_loop) captures the big one -- eliminating
     per-sentence launch/sync/memcpy overhead. This is the headline.
  2. KERNEL-only timing (us_per_sent_kernel) improves too, but for a different
     reason: K2 launches one tiny grid per sentence (~4.7% A100 occupancy in the
     Week-7 profile), while K3's cross-sentence launches saturate the GPU.
This script leads with the wall numbers, then shows the kernel/occupancy win.

Usage:
  python compare_k2_k3.py                       # defaults, cwd = cushr_gpu/
  python compare_k2_k3.py --k2 kbest_bench.csv --k3 batched_bench.csv --outdir .
"""
import argparse
import csv
import glob
import os
import re

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _num(v, cast=float):
    v = (v or "").strip()
    if v == "" or v.upper() == "NA":
        return None
    try:
        return cast(v)
    except ValueError:
        return None


def load_bench(path):
    """Return {K: rowdict} keyed by K. Missing file -> {}."""
    if not path or not os.path.exists(path):
        return {}
    out = {}
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            K = _num(r.get("K"), int)
            if K is None:
                continue
            out[K] = {
                "us_loop":      _num(r.get("us_per_sent_loop")),
                "us_kernel":    _num(r.get("us_per_sent_kernel")),
                "sent_per_sec": _num(r.get("sent_per_sec_kernel")),
                "used_MB":      _num(r.get("gpu_used_MB")),
                "table_MB":     _num(r.get("gpu_table_MB")),
            }
    return out


def fmt(v, spec="{:.1f}", na="—"):
    return na if v is None else spec.format(v)


def speedup(a, b):
    """a/b guarding None/zero. Returns None if not computable."""
    if a is None or b is None or b == 0:
        return None
    return a / b


def wall_sent_per_sec(row):
    """Derive wall-clock sent/sec from us_per_sent_loop (1e6 / us)."""
    u = row.get("us_loop")
    return (1e6 / u) if (u and u > 0) else None


def build_md(k2, k3, mem_sweep):
    Ks = sorted(set(k2) | set(k3))
    L = []
    L.append("# K2 (per-sentence) vs K3/K5 (batched) — Improvement\n")
    L.append("Auto-generated by `compare_k2_k3.py`. Leads with **wall-clock** "
             "throughput, because the batched win is the elimination of "
             "per-sentence launch/sync overhead — kernel-only timing excludes "
             "that overhead and looks ~identical between the two.\n")

    # ---- throughput (wall) ----
    L.append("## Throughput — wall clock (the headline)\n")
    L.append("| K | K2 wall µs/sent | K3 wall µs/sent | **wall speedup** | "
             "K2 sent/sec (wall) | K3 sent/sec (wall) |")
    L.append("|---|----------------:|----------------:|-----------------:|"
             "-------------------:|-------------------:|")
    for K in Ks:
        a, b = k2.get(K, {}), k3.get(K, {})
        su = speedup(a.get("us_loop"), b.get("us_loop"))
        L.append("| {K} | {a} | {b} | {su} | {as_} | {bs} |".format(
            K=K, a=fmt(a.get("us_loop")), b=fmt(b.get("us_loop")),
            su=(fmt(su, "{:.1f}x") if su else "—"),
            as_=fmt(wall_sent_per_sec(a), "{:.0f}"),
            bs=fmt(wall_sent_per_sec(b), "{:.0f}")))
    L.append("")

    # ---- throughput (kernel-only) ----
    L.append("## Throughput — kernel only (occupancy win)\n")
    L.append("Total merge *work* is identical, but K2 launches one tiny grid per "
             "sentence (Week-7 Nsight measured ~4.7% occupancy at K=32), so the "
             "A100 is starved. K3's cross-sentence launches saturate the GPU, so "
             "kernel-only throughput improves too — separately from the launch-"
             "overhead removal that the wall numbers above capture.\n")
    L.append("| K | K2 kernel µs/sent | K3 kernel µs/sent | kernel speedup |")
    L.append("|---|------------------:|------------------:|---------------:|")
    for K in Ks:
        a, b = k2.get(K, {}), k3.get(K, {})
        su = speedup(a.get("us_kernel"), b.get("us_kernel"))
        L.append("| {K} | {a} | {b} | {su} |".format(
            K=K, a=fmt(a.get("us_kernel")), b=fmt(b.get("us_kernel")),
            su=(fmt(su, "{:.2f}x") if su else "—")))
    L.append("")

    # ---- memory ----
    L.append("## Memory — fixed full-corpus (K2) vs chunked (K3)\n")
    L.append("K2 always allocates the whole-corpus top-K table. K3's `--batch N` "
             "sizes the table to one chunk, so device memory scales with the batch "
             "— run the full corpus within a fixed footprint.\n")
    L.append("| K | K2 used MB (full-N) | K3 used MB (batch=-1) | table MB @K2 | table MB @K3 |")
    L.append("|---|--------------------:|----------------------:|-------------:|-------------:|")
    for K in Ks:
        a, b = k2.get(K, {}), k3.get(K, {})
        L.append("| {K} | {a} | {b} | {ta} | {tb} |".format(
            K=K, a=fmt(a.get("used_MB")), b=fmt(b.get("used_MB")),
            ta=fmt(a.get("table_MB")), tb=fmt(b.get("table_MB"))))
    L.append("")

    if mem_sweep:
        L.append("### Memory vs batch size (K3, K=32)\n")
        L.append("Shows the chunked footprint shrinking as `--batch` drops, "
                 "against K2's fixed full-corpus allocation.\n")
        L.append("| batch | K3 used MB (K=32) |")
        L.append("|------:|------------------:|")
        for batch, used in mem_sweep:
            L.append(f"| {batch} | {fmt(used)} |")
        L.append("")

    L.append("![Throughput K2 vs K3](comparison_throughput.png)\n")
    if mem_sweep:
        L.append("![Memory vs batch](comparison_memory.png)\n")
    return "\n".join(L)


def plot_throughput(k2, k3, path):
    Ks = sorted(set(k2) | set(k3))
    if not Ks:
        return
    def series(d):
        return [wall_sent_per_sec(d.get(K, {})) for K in Ks]
    plt.figure(figsize=(5.2, 3.4))
    plt.plot(Ks, series(k2), "o--", color="#718096", label="K2 per-sentence (wall)")
    plt.plot(Ks, series(k3), "s-",  color="#2b6cb0", label="K3 batched (wall)")
    plt.xlabel("K (beam width)")
    plt.ylabel("Sentences / sec (wall clock)")
    plt.title("Throughput: K2 vs K3 (batched)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=140)
    plt.close()


def plot_memory(mem_sweep, k2_used_k32, path):
    if not mem_sweep:
        return
    xs = [b for b, _ in mem_sweep]
    ys = [u for _, u in mem_sweep]
    plt.figure(figsize=(5.2, 3.4))
    plt.plot(xs, ys, "s-", color="#c05621", label="K3 batched (K=32)")
    if k2_used_k32 is not None:
        plt.axhline(k2_used_k32, color="#718096", ls="--",
                    label=f"K2 fixed full-N ({k2_used_k32:.0f} MB)")
    plt.xlabel("--batch (sentences per chunk)")
    plt.ylabel("GPU used MB")
    plt.title("Device memory vs batch size (K=32)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=140)
    plt.close()


def load_mem_sweep(outdir, k_target=32):
    """Collect (batch, used_MB@K) from batched_bench_b<N>.csv + batched_bench.csv."""
    pts = []
    for path in glob.glob(os.path.join(outdir, "batched_bench_b*.csv")):
        m = re.search(r"batched_bench_b(\d+)\.csv$", os.path.basename(path))
        if not m:
            continue
        rows = load_bench(path)
        if k_target in rows and rows[k_target]["used_MB"] is not None:
            pts.append((int(m.group(1)), rows[k_target]["used_MB"]))
    # whole-corpus run = the largest batch point.
    whole = load_bench(os.path.join(outdir, "batched_bench.csv"))
    if k_target in whole and whole[k_target]["used_MB"] is not None:
        pts.append((max((b for b, _ in pts), default=0) * 4 or 999999,
                    whole[k_target]["used_MB"]))
    pts.sort()
    return pts


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--k2", default=os.path.join(here, "kbest_bench.csv"))
    ap.add_argument("--k3", default=os.path.join(here, "batched_bench.csv"))
    ap.add_argument("--outdir", default=here)
    ap.add_argument("--md", default="COMPARISON.md")
    args = ap.parse_args()

    k2 = load_bench(args.k2)
    k3 = load_bench(args.k3)
    if not k2 and not k3:
        raise SystemExit("neither CSV found. Run bench_kbest.slurm (kbest_bench.csv) "
                         "and bench_batched.slurm (batched_bench.csv) first.")

    mem_sweep = load_mem_sweep(args.outdir)
    k2_used_k32 = k2.get(32, {}).get("used_MB")

    plot_throughput(k2, k3, os.path.join(args.outdir, "comparison_throughput.png"))
    plot_memory(mem_sweep, k2_used_k32, os.path.join(args.outdir, "comparison_memory.png"))

    md = build_md(k2, k3, mem_sweep)
    md_path = os.path.join(args.outdir, args.md)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"wrote {md_path}")


if __name__ == "__main__":
    main()
