#!/usr/bin/env python3


import numpy as np
import torch
import torch.nn as nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

ENCODERS = {}

# Byte values are shifted up by one so that 0 can mean "padding" and never
# collides with a real character.
PAD_CHAR = 0
CHAR_OFFSET = 1


def register(name):
    def wrap(cls):
        cls.name = name
        ENCODERS[name] = cls
        return cls
    return wrap


def get(name, **kw):
    if name not in ENCODERS:
        raise KeyError(f"unknown encoder {name!r}; available: {sorted(ENCODERS)}")
    return ENCODERS[name](**kw)


@register("char_bilstm")
class CharBiLSTMEncoder(nn.Module):
    # takes a batch of raw character sequences
    # outputs fixed size context vector for each node/candidate word

    def __init__(self, n_chars=256, char_dim=32, hidden=128, layers=2,
                 out_dim=96, dropout=0.0):
        super().__init__()
        self.out_dim = out_dim

        # convert raw character integers into dense vector
        # CHAR_OFFSET is 1 to ensure that no character ever encodes to a 0
        # 0 in raw byte value means null padding space
        self.emb = nn.Embedding(n_chars + CHAR_OFFSET, char_dim, padding_idx=PAD_CHAR)

        # from the pytorch library torch.nn which is standard lib for building neural network
        # LSTM is type of RNN to process data and remember context as you maintain memory

        # char_dim is the length of vector for every character = 32
        # hidden is length of vector it will remember at every stage = 128
        # num_layers is how many LSTMs stacked = 2
        # bidirectional to create 2 LSTMs in parallel running L-R and R-L, final output will be 256
        # batch_first means to format data in the form of (batch size=64 sent, sequence length=40 char/sent, features=32 nums/char)
        # dropout if layers > 1 else 0.0. drouput is a technique to randomly turn off neurons to prevent memorizing/overfitting
            # applies dropout value if 2+ layers
        self.lstm = nn.LSTM(char_dim, hidden, num_layers=layers,
                            bidirectional=True, batch_first=True,
                            dropout=dropout if layers > 1 else 0.0)

        # each endpoint has forward/backward lstm vector so 128+128 = 256
        # 2 endpoints -> 512 = 4*hidden = size of tensor entering final linear layer
        self.span = nn.Linear(4 * hidden, out_dim)

    def forward(self, chars, char_len, node_sent, span_start, span_end,
                char_ok):
        """chars [B, L] int64 (0 = pad); returns [n_nodes, out_dim]."""
        h = self.emb(chars)
        lengths = char_len.detach().cpu().clamp(min=1)
        packed = pack_padded_sequence(h, lengths, batch_first=True, enforce_sorted=False)
        out, _ = self.lstm(packed)
        H, _ = pad_packed_sequence(out, batch_first=True, total_length=chars.shape[1])

        # first and last character together give me the left context + word and right context + word
        first = H[node_sent, span_start]  # [n, 2*hidden]
        last = H[node_sent, span_end - 1]  # [n, 2*hidden]

        # concatenate boundary char states together
        ctx = self.span(torch.cat([first, last], dim=-1))
        # Boundary nodes carry no signal, matching every other featurizer.
        return ctx.masked_fill(~char_ok.unsqueeze(-1), 0.0)


# put model together
class ContextualBiaffine(nn.Module):

    def __init__(self, featurizer, encoder, scorer):
        super().__init__()

        # takes existing pre computed features thru featurizer
        self.featurizer = featurizer
        self.encoder = encoder
        self.scorer = scorer


    def node_vectors(self, feats, ids, batch):
        base = (self.featurizer(feats, ids) if self.featurizer is not None
                else feats)
        ctx = self.encoder(batch["chars"], batch["char_len"],
                           batch["node_sent"], batch["span_start"],
                           batch["span_end"], batch["char_ok"])

        # concatenates base features with new context-aware features generated by encoder
        return torch.cat([base, ctx], dim=-1)

    # pass in the concatenated vector to scorer (Biaffine) to predict probability that node A
    # connects to B in the final segmentation graph
    def forward(self, feats, src, dst, ids=None, batch=None):
        if batch is None:
            raise ValueError(
                "ContextualBiaffine needs the batch dict for character "
                "context; call model(feats, src, dst, ids, batch)")
        return self.scorer.edge_scores(self.node_vectors(feats, ids, batch),
                                       src, dst)

    def num_params(self):
        return sum(p.numel() for p in self.parameters())


# runs the neural network once over the entire corpus in mini batches
# extracts final 192 dim vectors for each node and freeze them into numpy arr
@torch.no_grad()
def materialize_contextual(model, store, device, out, sent_chunk=256):
    from dataset import collate

    model.eval()
    n_sent = len(store.sent_off) - 1
    for lo in range(0, n_sent, sent_chunk):
        ids = np.arange(lo, min(lo + sent_chunk, n_sent), dtype=np.int64)
        b = collate(store, ids)
        t = {
            "chars": torch.as_tensor(b["chars"], dtype=torch.int64, device=device),
            "char_len": torch.as_tensor(b["char_len"], dtype=torch.int64, device=device),
            "node_sent": torch.as_tensor(b["node_sent"], dtype=torch.int64, device=device),
            "span_start": torch.as_tensor(b["span_start"], dtype=torch.int64, device=device),
            "span_end": torch.as_tensor(b["span_end"], dtype=torch.int64, device=device),
            "char_ok": torch.as_tensor(b["char_ok"], dtype=torch.bool, device=device),
        }
        feats = torch.as_tensor(np.asarray(b["feats"]), dtype=torch.float32,
                                device=device)
        nid = (torch.as_tensor(np.asarray(b["ids"]), dtype=torch.int64,
                               device=device)
               if b.get("ids") is not None else None)
        out[b["global_node"]] = model.node_vectors(feats, nid, t).cpu().numpy()
    model.train()
    return out
